services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: productDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d productDatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: productDatabase
      SERVER_PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/go/src/app
    command: ["go", "run", "/product-service/cmd/server/main.go"]

volumes:
  postgres_data:
    driver: local
  pgdata:
